# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2

commands:
  setup_python:
    parameters:
      version:
        type: string
        default: "3.7"
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install libpulse-dev
      - restore_cache:
          keys:
            - py<< parameters.version >>-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - py<< parameters.version >>-dependencies-
      - run:
          name: Install Python deps in a venv
          command: |
            poetry install
      - save_cache:
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
          key: py<< parameters.version >>-dependencies-{{ checksum "poetry.lock" }}

jobs:
  black-lint:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/i3pyblocks
    steps:
      - setup_python
      - run:
          name : Run lint
          command: |
            poetry run black --check .

  flake8-lint:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/i3pyblocks
    steps:
      - setup_python
      - run:
          name : Run lint
          command: |
            poetry run flake8 .

  build-python36:
    docker:
      - image: circleci/python:3.6.9
    working_directory: ~/i3pyblocks
    steps:
      - setup_python:
          version: "3.6"
      - run:
          name : Run tests
          command: |
            poetry run pytest -vv --mypy-ignore-missing-imports --cov=i3pyblocks --cov-report=term --cov-report=xml tests/
      - codecov/upload:
          file: coverage.xml

  build-python37:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/i3pyblocks
    steps:
      - setup_python:
          version: "3.7"
      - run:
          name : Run tests
          command: |
            poetry run pytest -vv --mypy-ignore-missing-imports --cov=i3pyblocks --cov-report=term --cov-report=xml tests/
      - codecov/upload:
          file: coverage.xml

workflows:
  build:
    jobs:
      - black-lint
      - flake8-lint
      - build-python36
      - build-python37
