# https://github.com/grst/python-ci-versioneer
# https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
name: Publish

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Autobump version
      run: |
        # from refs/tags/v1.2.3 get 1.2.3
        VERSION="${GITHUB_REF##*/}"
        VERSION_FILE='i3pyblocks/__version__.py'
        echo "__version__ = \"${VERSION}\"" > "${VERSION_FILE}"
      shell: bash

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pep517

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pep517.build --source --binary --out-dir dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        password: ${{ secrets.pypi_password }}

    - name: Commit new development version
      run: |
        # from refs/tags/v1.2.3 get 1.2.3
        VERSION="${GITHUB_REF##*/}-dev"
        VERSION_FILE='i3pyblocks/__version__.py'
        echo "__version__ = \"${VERSION}\"" > "${VERSION_FILE}"
      shell: bash

    - name: Create PR to bump version
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Bump version
        title: Bump version
        body: Bump development version.
        branch: bump-version
        base: master
