name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: $GITHUB_WORKSPACE/venv
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-py${{ matrix.python-version }}-pip-
          ${{ runner.os }}-py${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Necessary for pulsectl
        sudo apt-get install libpulse-dev
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        make dev-install

    - name: Run linters
      run: |
        make lint

    - name: Test with pytest
      run: |
        make test-coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
